#!/usr/bin/env python3
"""Binary-search the largest safe MultiViewGenerator.max_size (VRAM probe).

max_size is the per-view point-count budget for Sonata-style SSL pretraining
(see pointcept/datasets/transform.py, class MultiViewGenerator): each global/
local view draws size = int(scale * max_size) points, so it is the dominant
per-sample VRAM lever, independent of grid_size. Unlike batch_size, it is set
inline inside the transform list (data.train.transform[i]["max_size"]), not
as a top-level config key.

Config._file2dict (the `_base_ = [...]` merge path, pointcept/utils/config.py)
does not pass allow_list_keys=True, so a generated overlay `_base_` config
cannot override a list element by index. Only Config.merge_from_dict (used by
tools/train.py's --options) supports that. This script therefore keeps
batch_size / mix_prob / schedule overrides in a generated overlay config (like
scripts/find_max_batch_size.py does), but injects the max_size trial value via
--options data.train.transform.<idx>.max_size=<V> on the tools/train.py CLI.

Train-only (Sonata SSL pretrain has no online eval). batch_size_per_gpu is
FIXED (not searched) — pass the batch_size_per_gpu you intend to actually
train with, so the VRAM probe reflects that batch size.

Views are sampled stochastically: size = int(np.random.uniform(*scale) *
max_size). By default this script forces global_view_scale=[1.0, 1.0] on every
trial so each probe deterministically hits the worst case (exactly max_size
points per global view) instead of possibly getting lucky on a short probe.
Disable with --no-force-worst-case-scale to measure the average case instead.

enc2d_max_size is out of scope: the Flair3D+ MultiViewGenerator config never
sets view_keys to include "correspondence", so the if_enc2d branch in
get_view() (transform.py) is unreachable for this dataset.

Examples::

  # Resolve the transform index + preview the first trial, no GPU needed
  python scripts/find_max_view_size.py \\
    --config-file configs/flair3d_default/pretrain-sonata-v1m2-flair3d.py \\
    --dry-run

  # Fast smoke test on the debug config (small dataset, few steps)
  python scripts/find_max_view_size.py \\
    --config-file configs/flair3d_default/pretrain-sonata-v1m2-flair3d-debug.py \\
    --min-max-size 4096 --max-max-size 16384 --probe-steps 8 --soak-steps 0

  # Bracket around the known OOM (job 546886 crashed at max_size=65536,
  # batch_size_per_gpu=2); batch_size_per_gpu=3 here is strictly worse
  python scripts/find_max_view_size.py \\
    --config-file configs/flair3d_default/pretrain-sonata-v1m2-flair3d.py \\
    --min-max-size 32768 --max-max-size 65536 --probe-steps 16 --soak-steps 0 \\
    --batch-size-per-gpu 3

  # Full search with soak, matching the target batch_size=96 (32 GPU x 3)
  python scripts/find_max_view_size.py \\
    --config-file configs/flair3d_default/pretrain-sonata-v1m2-flair3d.py \\
    --min-max-size 8192 --max-max-size 49152 \\
    --batch-size-per-gpu 3 --probe-steps 16 --soak-steps 300
"""

from __future__ import annotations

import argparse
import csv
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

OOM_PATTERNS = (
    "cuda out of memory",
    "out of memory",
    "cublas_status_alloc_failed",
    "cudnn_status_alloc_failed",
    "hip out of memory",
)

MAX_MEM_RE = re.compile(r"max_mem:\s*([0-9]+(?:\.[0-9]+)?)M")


def log(msg: str) -> None:
    print(msg, flush=True)


def resolve_transform_index(
    config_file: Path, transform_type: str, manual_index: int | None
) -> int:
    if manual_index is not None:
        return manual_index
    from pointcept.utils.config import Config

    cfg = Config.fromfile(str(config_file))
    transform = cfg.data.train.transform
    matches = [i for i, t in enumerate(transform) if t.get("type") == transform_type]
    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one transform with type={transform_type!r} in "
            f"data.train.transform, found {len(matches)} (indices={matches}). "
            f"Use --transform-index to override."
        )
    return matches[0]


def build_hooks() -> list[dict]:
    """Minimal train-only hook list for VRAM probes.

    Fully replaces the source config ``hooks`` in the overlay, so side-effect
    hooks (e.g. ``LinProbeSbatchHook``) are disabled during the search.
    """
    return [
        dict(type="CheckpointLoader"),
        dict(type="ModelHook"),
        dict(type="IterationTimer", warmup_iter=2),
        dict(type="InformationWriter"),
    ]


def write_probe_config(*, src_config: Path, dest: Path, overrides: dict) -> None:
    """Write a thin _base_ config so we do not re-import heavy deps here."""
    src_abs = str(src_config.resolve())
    lines = [
        "# Auto-generated by scripts/find_max_view_size.py — do not edit.",
        f"_base_ = [{src_abs!r}]",
    ]
    for key, value in overrides.items():
        lines.append(f"{key} = {repr(value)}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_peak_mem_mb(text: str) -> float | None:
    matches = MAX_MEM_RE.findall(text)
    if not matches:
        return None
    return max(float(x) for x in matches)


def is_oom(text: str, returncode: int) -> bool:
    low = text.lower()
    return any(p in low for p in OOM_PATTERNS)


def run_cmd(
    cmd: list[str],
    *,
    cwd: Path,
    log_path: Path,
    timeout_s: int | None,
) -> tuple[int, str, float | None]:
    log(f"$ {shlex.join(cmd)}")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    t0 = time.perf_counter()
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            env=None,
        )
    except subprocess.TimeoutExpired as exc:
        out = (exc.stdout or "") + (exc.stderr or "")
        log_path.write_text(out, encoding="utf-8")
        raise
    out = (proc.stdout or "") + (proc.stderr or "")
    log_path.write_text(out, encoding="utf-8")
    elapsed = time.perf_counter() - t0
    peak = parse_peak_mem_mb(out)
    log(
        f"  -> exit={proc.returncode} elapsed={elapsed:.1f}s "
        f"peak_mem={peak if peak is not None else 'n/a'}M "
        f"log={log_path}"
    )
    return proc.returncode, out, peak


def python_train_cmd(
    *, python: str, config_file: Path, num_gpus: int, extra_options: list[str]
) -> list[str]:
    cmd = [
        python,
        str(REPO_ROOT / "tools" / "train.py"),
        "--config-file",
        str(config_file),
        "--num-gpus",
        str(num_gpus),
    ]
    if extra_options:
        cmd.append("--options")
        cmd.extend(extra_options)
    return cmd


def build_trial_options(
    args: argparse.Namespace, transform_idx: int, max_size: int
) -> list[str]:
    options = [f"data.train.transform.{transform_idx}.max_size={int(max_size)}"]
    if args.force_worst_case_scale:
        options.append(f"data.train.transform.{transform_idx}.global_view_scale=[1.0,1.0]")
    options.extend(args.extra_options)
    return options


def probe_max_size(
    *,
    args: argparse.Namespace,
    work_dir: Path,
    trial_name: str,
    max_size: int,
    steps: int,
    transform_idx: int,
) -> tuple[bool, float | None, str]:
    """Run a short train probe at a given max_size. Returns (ok, peak_mem_mb, status)."""
    save_path = work_dir / "runs" / trial_name
    cfg_path = work_dir / "configs" / f"{trial_name}.py"

    overrides = {
        "batch_size": int(args.batch_size_per_gpu),
        "mix_prob": float(args.mix_prob),
        "total_iters": int(steps),
        "iter_per_epoch": int(steps),
        "evaluate": False,
        "enable_wandb": False,
        "save_path": str(save_path),
        "hooks": build_hooks(),
        "empty_cache": False,
        "empty_cache_per_epoch": False,
    }
    if args.num_worker is not None:
        overrides["num_worker"] = int(args.num_worker)

    write_probe_config(src_config=Path(args.config_file), dest=cfg_path, overrides=overrides)

    options = build_trial_options(args, transform_idx, max_size)
    cmd = python_train_cmd(
        python=args.python,
        config_file=cfg_path,
        num_gpus=args.num_gpus,
        extra_options=options,
    )
    log_path = work_dir / "logs" / f"{trial_name}.log"
    try:
        code, out, peak = run_cmd(cmd, cwd=REPO_ROOT, log_path=log_path, timeout_s=args.timeout)
    except subprocess.TimeoutExpired:
        return False, None, "timeout"

    if code == 0:
        return True, peak, "ok"
    if is_oom(out, code):
        return False, peak, "oom"
    return False, peak, f"error_exit_{code}"


def binary_search(args: argparse.Namespace, work_dir: Path, transform_idx: int) -> dict:
    lo, hi = int(args.min_max_size), int(args.max_max_size)
    if lo > hi:
        raise ValueError(f"Invalid search range: --min-max-size={lo} > --max-max-size={hi}")

    trials: list[dict] = []
    best = None
    best_peak = None
    trial_i = 0

    log(f"Phase 1: binary search max_size in [{lo}, {hi}] (transform index={transform_idx})")
    while lo <= hi:
        mid = (lo + hi) // 2
        trial_i += 1
        name = f"probe_{trial_i:02d}_ms{mid}"
        log(f"\n=== Probe {name} (lo={lo} hi={hi}) ===")
        ok, peak, status = probe_max_size(
            args=args,
            work_dir=work_dir,
            trial_name=name,
            max_size=mid,
            steps=args.probe_steps,
            transform_idx=transform_idx,
        )
        trials.append(
            dict(phase="probe", trial=name, max_size=mid, ok=ok, status=status, peak_mem_mb=peak)
        )
        if status.startswith("error_exit") or status == "timeout":
            raise RuntimeError(
                f"Non-OOM failure at max_size={mid} status={status}. "
                f"Inspect {work_dir / 'logs' / (name + '.log')}"
            )
        if ok:
            best = mid
            best_peak = peak
            lo = mid + 1
        else:
            hi = mid - 1

    if best is None:
        log("No max_size in range succeeded.")
        return dict(
            candidate_max_size=None,
            confirmed_max_size=None,
            peak_mem_mb=None,
            trials=trials,
        )

    log(f"\nPhase 1 candidate: max_size={best} peak_mem={best_peak}")

    confirmed = best
    confirmed_peak = best_peak
    if args.soak_steps > 0:
        log(f"\nPhase 2: soak up to {args.soak_steps} steps")
        while confirmed is not None and confirmed >= int(args.min_max_size):
            name = f"soak_ms{confirmed}"
            log(f"\n=== Soak {name} ===")
            ok, peak, status = probe_max_size(
                args=args,
                work_dir=work_dir,
                trial_name=name,
                max_size=confirmed,
                steps=args.soak_steps,
                transform_idx=transform_idx,
            )
            trials.append(
                dict(
                    phase="soak",
                    trial=name,
                    max_size=confirmed,
                    ok=ok,
                    status=status,
                    peak_mem_mb=peak,
                )
            )
            if status.startswith("error_exit") or status == "timeout":
                raise RuntimeError(f"Non-OOM failure during soak max_size={confirmed} status={status}")
            if ok:
                confirmed_peak = peak if peak is not None else confirmed_peak
                break
            confirmed = confirmed - 1 if confirmed - 1 >= int(args.min_max_size) else None
        if confirmed is None:
            log("Soak failed for all candidates.")

    return dict(
        candidate_max_size=best,
        confirmed_max_size=confirmed,
        peak_mem_mb=confirmed_peak,
        trials=trials,
    )


def write_csv(path: Path, args: argparse.Namespace, result: dict, transform_idx: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "config",
        "gpu_name",
        "transform_index",
        "batch_size_per_gpu",
        "mix_prob",
        "force_worst_case_scale",
        "candidate_max_size",
        "confirmed_max_size",
        "peak_mem_mb",
        "probe_steps",
        "soak_steps",
        "trial",
        "phase",
        "max_size",
        "ok",
        "status",
        "trial_peak_mem_mb",
    ]
    gpu_name = _gpu_name()
    common = {
        "config": args.config_file,
        "gpu_name": gpu_name,
        "transform_index": transform_idx,
        "batch_size_per_gpu": args.batch_size_per_gpu,
        "mix_prob": args.mix_prob,
        "force_worst_case_scale": args.force_worst_case_scale,
        "candidate_max_size": result["candidate_max_size"],
        "confirmed_max_size": result["confirmed_max_size"],
        "peak_mem_mb": result["peak_mem_mb"],
        "probe_steps": args.probe_steps,
        "soak_steps": args.soak_steps,
    }
    rows = []
    if not result["trials"]:
        rows.append(
            {**common, "trial": "", "phase": "", "max_size": "", "ok": "", "status": "", "trial_peak_mem_mb": ""}
        )
    else:
        for t in result["trials"]:
            rows.append(
                {
                    **common,
                    "trial": t["trial"],
                    "phase": t["phase"],
                    "max_size": t["max_size"],
                    "ok": t["ok"],
                    "status": t["status"],
                    "trial_peak_mem_mb": t["peak_mem_mb"],
                }
            )
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    log(f"Wrote CSV: {path}")


def _gpu_name() -> str:
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"], text=True
        ).strip()
        return out.splitlines()[0] if out else "unknown"
    except Exception:
        return "unknown"


def preview_trial(args: argparse.Namespace, work_dir: Path, transform_idx: int) -> None:
    mid = (int(args.min_max_size) + int(args.max_max_size)) // 2
    name = f"dry_run_ms{mid}"
    save_path = work_dir / "runs" / name
    cfg_path = work_dir / "configs" / f"{name}.py"
    overrides = {
        "batch_size": int(args.batch_size_per_gpu),
        "mix_prob": float(args.mix_prob),
        "total_iters": int(args.probe_steps),
        "iter_per_epoch": int(args.probe_steps),
        "evaluate": False,
        "enable_wandb": False,
        "save_path": str(save_path),
        "hooks": build_hooks(),
        "empty_cache": False,
        "empty_cache_per_epoch": False,
    }
    if args.num_worker is not None:
        overrides["num_worker"] = int(args.num_worker)
    write_probe_config(src_config=Path(args.config_file), dest=cfg_path, overrides=overrides)
    options = build_trial_options(args, transform_idx, mid)
    cmd = python_train_cmd(
        python=args.python, config_file=cfg_path, num_gpus=args.num_gpus, extra_options=options
    )

    log(f"Resolved transform index: {transform_idx}")
    log(f"Search range: [{args.min_max_size}, {args.max_max_size}] (first mid trial: max_size={mid})")
    log(f"\n--- Overlay config: {cfg_path} ---")
    log(cfg_path.read_text(encoding="utf-8"))
    log(f"--- Command that would run ---\n$ {shlex.join(cmd)}")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--config-file", required=True, help="Path to Pointcept config .py")
    p.add_argument(
        "--transform-type",
        type=str,
        default="MultiViewGenerator",
        help="Transform type to locate in data.train.transform",
    )
    p.add_argument(
        "--transform-index",
        type=int,
        default=None,
        help="Manual override if auto-detection is ambiguous/fails",
    )
    p.add_argument("--min-max-size", type=int, default=8192)
    p.add_argument("--max-max-size", type=int, default=49152)
    p.add_argument(
        "--batch-size-per-gpu",
        type=int,
        default=3,
        help="Fixed batch_size_per_gpu for the probe (not searched)",
    )
    p.add_argument(
        "--mix-prob",
        type=float,
        default=0.0,
        help="Train Mix3D probability (default 0 = Sonata SSL pretrain, no Mix3D)",
    )
    p.add_argument(
        "--force-worst-case-scale",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Force global_view_scale=[1.0,1.0] per trial so views deterministically hit "
        "max_size points (default on); disable to measure the average/stochastic case",
    )
    p.add_argument(
        "--probe-steps", type=int, default=16, help="Train steps per dichotomie trial"
    )
    p.add_argument(
        "--soak-steps",
        type=int,
        default=300,
        help="Longer re-verification of the candidate max_size (0 to skip)",
    )
    p.add_argument("--num-gpus", type=int, default=1)
    p.add_argument("--num-worker", type=int, default=None, help="Override num_worker")
    p.add_argument(
        "--work-dir",
        type=str,
        default=None,
        help="Directory for temp configs / logs / CSV (default under exp/)",
    )
    p.add_argument("--csv", type=str, default=None, help="Output CSV path")
    p.add_argument("--python", type=str, default=sys.executable)
    p.add_argument(
        "--timeout", type=int, default=None, help="Per-trial timeout in seconds (default: none)"
    )
    p.add_argument(
        "--extra-options",
        nargs="*",
        default=[],
        help="Extra Pointcept --options key=value pairs",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Resolve the transform index and preview the first trial, then exit (no subprocess)",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    config_file = Path(args.config_file)
    if not config_file.is_file():
        alt = REPO_ROOT / args.config_file
        if alt.is_file():
            args.config_file = str(alt)
            config_file = alt
        else:
            log(f"Config not found: {args.config_file}")
            return 2

    if args.mix_prob != 0:
        log(
            "NOTE: mix_prob!=0 — this script defaults to 0 for Sonata SSL pretrain "
            "(no Mix3D). Only pass a non-zero value if the real training config does too."
        )

    try:
        transform_idx = resolve_transform_index(config_file, args.transform_type, args.transform_index)
    except Exception as exc:
        log(f"ERROR resolving transform index: {exc}")
        return 2

    stamp = time.strftime("%Y%m%d_%H%M%S")
    cfg_stem = config_file.stem
    work_dir = Path(
        args.work_dir or (REPO_ROOT / "exp" / "max_size_search" / f"{cfg_stem}_{stamp}")
    )
    work_dir.mkdir(parents=True, exist_ok=True)
    log(f"Work dir: {work_dir}")
    log(f"Config: {config_file}")
    log(f"GPU: {_gpu_name()}")
    log(
        f"transform_index={transform_idx} batch_size_per_gpu={args.batch_size_per_gpu} "
        f"force_worst_case_scale={args.force_worst_case_scale}"
    )

    if args.dry_run:
        preview_trial(args, work_dir, transform_idx)
        return 0

    try:
        result = binary_search(args, work_dir, transform_idx)
    except Exception as exc:
        log(f"ERROR: {exc}")
        return 1

    csv_path = Path(args.csv) if args.csv else work_dir / "results.csv"
    write_csv(csv_path, args, result, transform_idx)

    log("\n======== SUMMARY ========")
    log(f"candidate_max_size={result['candidate_max_size']}")
    log(f"confirmed_max_size={result['confirmed_max_size']}")
    log(f"peak_mem_mb={result['peak_mem_mb']}")
    if result["confirmed_max_size"] is not None:
        log(
            f"Suggested config: max_size = {result['confirmed_max_size']}  "
            f"(probed with batch_size_per_gpu={args.batch_size_per_gpu}, "
            f"force_worst_case_scale={args.force_worst_case_scale})"
        )
    else:
        log("No confirmed max_size — lower --min-max-size / check logs.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
