"""
Batch-generate 10-seed GridProbe ensemble configs under
configs/experiment/w110/2/grid_seed_{h3d,eclair,dales}/ from the existing
12-probe lr-grid GridProbeSegmentorV2 reference configs, fixing lr at each
(model, dataset)'s already-established sweep winner.

Mirrors tools/gen_flair3d_mono_configs.py's batch-regeneration pattern: a
small per-row table drives a text transform applied to each reference file,
rather than hand-writing ~27 near-duplicate configs.

Transform applied to every reference file's raw text:
  1. Replace the probes-defining block (from `_losses = {`/`_criteria = [`
     through the last `del ...` line) with a flat 10-probe
     `ce_lovasz_init{i}` dict at the fixed lr (same pattern already applied
     by hand to configs/dales/sonata-v1m2-dales-lin-grid.py this session).
  2. Replace the `wandb_run_name` f-string: "GridProbe" -> "SeedEnsemble",
     "{len(probes)} probes" -> "{len(probes)} inits, lr=<lr>".
  3. Replace the hooks tail: GridProbeWinnerSelector -> GridProbeSeedEnsembleTester.
  4. Insert `test = dict(type="GridProbeSemSegTester", verbose=True)` after hooks.
  5. Fix `_base_`, `grp_exp`, `num_exp` for the new file's location.
  6. Prepend a short docstring note describing the seed-ensemble conversion.

Run once: `python tools/gen_grid_seed_configs.py`. Idempotent (overwrites its
own output files only).
"""

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_BASE = "../../../../_base_/default_runtime.py"

PROBES_BLOCK_RE = re.compile(
    r"\n(?:#[^\n]*\n)+"                        # comment header (1+ lines)
    r"_(?:losses|criteria) = [\[{].*?"         # start of probe axis defs
    r"\ndel [^\n]*\n(?:del [^\n]*\n)*"         # one or more `del ...` lines
    r"\n*wandb_run_name = \(.*?\n\)\n",        # through wandb_run_name's closing paren
    re.DOTALL,
)

HOOKS_TAIL_RE = re.compile(
    r'dict\(type="GridProbeWinnerSelector"(?:, skip_test=(?:True|False))?\),\n\]'
)

DOCSTRING_NOTE = (
    "SEED-ENSEMBLE (generated by tools/gen_grid_seed_configs.py): converted from the "
    "12-probe lr-grid reference below into 10 probes with IDENTICAL hyperparameters "
    "(lr fixed at that sweep's winner), differing only by random init -- to report "
    "test mIoU/mAcc/allAcc as mean+/-std across seeds. Reuses GridProbe's shared "
    "frozen-backbone forward purely to avoid paying the backbone cost 10x. Original "
    "reference docstring below.\n\n"
)


def build_probes_block(lr: float) -> str:
    return f"""
# Seed-ensemble probes — ce_lovasz, AdamW/wd0/OneCycleLR warmup5%, lr fixed at the
# best value from the earlier lr-grid sweep; only the random init differs across
# probes (each ProbeHead.linear draws its own init from sequential construction in
# GridProbeSegmentorV2.__init__ — no explicit seed field needed).
_criteria = [
    dict(type="CrossEntropyLoss", loss_weight=1.0, ignore_index=ignore_index),
    dict(type="LovaszLoss", mode="multiclass", loss_weight=1.0, ignore_index=ignore_index),
]

probes = {{
    f"ce_lovasz_init{{i}}": dict(
        criteria=_criteria,
        input_norm=None,
        feat_norm=None,
        dropout=0.0,
        optimizer=dict(type="AdamW", lr={lr!r}, weight_decay=0.0),
        scheduler=dict(
            type="OneCycleLR",
            max_lr={lr!r},
            pct_start=0.05,
            anneal_strategy="cos",
            div_factor=10.0,
            final_div_factor=1000.0,
        ),
        grad_clip=3.0,
    )
    for i in range(10)
}}
del _criteria

wandb_run_name = ("""


def transform(text: str, *, lr: float, num_exp: int) -> str:
    m = PROBES_BLOCK_RE.search(text)
    assert m, "probes block markers not found — reference file shape changed?"

    # Recover the wandb_run_name f-string body (between the opening "(" this
    # regex stopped at and its own closing ")") so we can reuse it, tweaked.
    wandb_start = text.index("wandb_run_name = (", m.start())
    wandb_close = text.index("\n)\n", wandb_start) + len("\n)\n")
    wandb_body = text[wandb_start + len("wandb_run_name = (") : wandb_close - len("\n)\n")]
    wandb_body = wandb_body.replace("GridProbe ", "SeedEnsemble ")
    wandb_body = re.sub(
        r"\{len\(probes\)\} probes", f"{{len(probes)}} inits, lr={lr!r}", wandb_body
    )

    new_block = build_probes_block(lr) + wandb_body + "\n)\n"
    text = text[: m.start()] + "\n" + new_block + text[wandb_close:]

    hm = HOOKS_TAIL_RE.search(text)
    assert hm, "hooks tail (GridProbeWinnerSelector) not found"
    text = (
        text[: hm.start()]
        + 'dict(type="GridProbeSeedEnsembleTester"),\n]'
        + text[hm.end() :]
    )

    # Insert `test = ...` right after the hooks list's closing "]".
    hooks_close = text.index("]", hm.start()) + 1
    insert = (
        "\n\n# Override default_runtime.py's test = dict(type=\"SemSegTester\", ...): the\n"
        "# seed-ensemble test pass needs the shared-backbone, all-probes-at-once tester.\n"
        'test = dict(type="GridProbeSemSegTester", verbose=True)'
    )
    text = text[:hooks_close] + insert + text[hooks_close:]

    # The reference files' top-level `lr = 5e-2` is a dummy/leftover value never
    # actually consumed by the lr-grid (the sweep read lr from _lrs instead) —
    # but it reads as "the lr" and caused exactly that confusion once already
    # this session. Point it at the real fixed value so it can't mislead again.
    text = re.sub(
        r"^lr = [^\n#]+$",
        f"lr = {lr!r}  # fixed at the lr-grid sweep winner (see docstring)",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    text = re.sub(r'^_base_ = \[.*\]$', f'_base_ = ["{OUT_BASE}"]', text, count=1, flags=re.MULTILINE)
    text = re.sub(r"^grp_exp = \d+$", "grp_exp = 2", text, count=1, flags=re.MULTILINE)
    text = re.sub(r"^num_exp = \d+$", f"num_exp = {num_exp}", text, count=1, flags=re.MULTILINE)
    text = re.sub(r'^"""\n', '"""\n' + DOCSTRING_NOTE, text, count=1)
    return text


def read_ref(ref: str) -> str:
    """`ref` is either a repo-relative path (read from the working tree) or
    "git:HEAD:<path>" (read from git history — used for
    configs/dales/sonata-v1m2-dales-lin-grid.py, whose working-tree copy is
    already the hand-converted seed-ensemble from earlier this session)."""
    if ref.startswith("git:"):
        _, rev, path = ref.split(":", 2)
        return subprocess.run(
            ["git", "show", f"{rev}:{path}"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
        ).stdout
    return (REPO_ROOT / ref).read_text()


ROWS = [
    # (num_exp, slug, dataset, ref, lr)
    (1, "sonata-v1m2", "h3d", "configs/h3d/sonata-v1m2-h3d-lin-grid.py", 0.02),
    (1, "sonata-v1m2", "eclair", "configs/eclair/sonata-v1m2-eclair-lin-grid.py", 0.02),
    (1, "sonata-v1m2", "dales", "git:HEAD:configs/dales/sonata-v1m2-dales-lin-grid.py", 0.02),
    (2, "litept-b-v1m0", "h3d", "configs/h3d/litept-b-v1m0-h3d-lin_enc.py", 0.005),
    (2, "litept-b-v1m0", "eclair", "configs/eclair/litept-b-v1m0-eclair-lin_enc.py", 0.01),
    (2, "litept-b-v1m0", "dales", "configs/dales/litept-b-v1m0-dales-lin-grid-enc.py", 0.02),
    (3, "ptv3-v1m0", "h3d", "configs/h3d/ptv3-v1m0-h3d-lin-grid-enc.py", 0.01),
    (3, "ptv3-v1m0", "eclair", "configs/eclair/ptv3-v1m0-eclair-lin-grid-enc.py", 0.002),
    (3, "ptv3-v1m0", "dales", "configs/dales/ptv3-v1m0-dales-lin-grid-enc.py", 0.002),
    (4, "kpconvx-v1m0", "h3d", "configs/h3d/kpconvx-v1m0-h3d-lin-grid-enc.py", 0.05),
    (4, "kpconvx-v1m0", "eclair", "configs/eclair/kpconvx-v1m0-eclair-lin-grid-enc.py", 0.01),
    (4, "kpconvx-v1m0", "dales", "configs/dales/kpconvx-v1m0-dales-lin-grid-enc.py", 0.05),
    (5, "spunet-v1m0", "h3d", "configs/h3d/spunet-v1m0-h3d-lin-grid-enc.py", 0.01),
    (5, "spunet-v1m0", "eclair", "configs/eclair/spunet-v1m0-eclair-lin-grid-enc.py", 0.01),
    (5, "spunet-v1m0", "dales", "configs/dales/spunet-v1m0-dales-lin-grid-enc.py", 0.005),
    (6, "litept-b-v1m0-noGNL", "h3d", "configs/experiment/w110/1/abla_grid_on_h3d/litept-b-v1m0-h3d-lin_enc_1.py", 0.005),
    (6, "litept-b-v1m0-noGNL", "eclair", "configs/experiment/w110/1/abla_grid_on_eclair/litept-b-v1m0-eclair-lin_enc_1.py", 0.5),
    (6, "litept-b-v1m0-noGNL", "dales", "configs/experiment/w110/1/abla_grid_on_dales/litept-b-v1m0-dales-lin-grid-enc_1.py", 0.01),
    (7, "litept-b-v1m0-monoLC", "h3d", "configs/experiment/w110/1/abla_grid_on_h3d/litept-b-v1m0-h3d-lin_enc_2.py", 0.02),
    (7, "litept-b-v1m0-monoLC", "eclair", "configs/experiment/w110/1/abla_grid_on_eclair/litept-b-v1m0-eclair-lin_enc_2.py", 0.02),
    (7, "litept-b-v1m0-monoLC", "dales", "configs/experiment/w110/1/abla_grid_on_dales/litept-b-v1m0-dales-lin-grid-enc_2.py", 0.02),
    (8, "litept-b-v1m0-monoElev", "h3d", "configs/experiment/w110/1/abla_grid_on_h3d/litept-b-v1m0-h3d-lin_enc_3.py", 0.01),
    (8, "litept-b-v1m0-monoElev", "eclair", "configs/experiment/w110/1/abla_grid_on_eclair/litept-b-v1m0-eclair-lin_enc_3.py", 0.005),
    (8, "litept-b-v1m0-monoElev", "dales", "configs/experiment/w110/1/abla_grid_on_dales/litept-b-v1m0-dales-lin-grid-enc_3.py", 0.02),
    (9, "litept-b-v1m0-SS", "h3d", "configs/h3d/litept-b-v1m0-h3d-lin_dec_ss.py", 0.1),
    (9, "litept-b-v1m0-SS", "dales", "configs/dales/litept-b-v1m0-dales-lin-grid-dec-ss.py", 0.1),
]

NAME_TEMPLATES = {
    (1, "h3d"): "sonata-v1m2-h3d-lin-grid-seed_1.py",
    (1, "eclair"): "sonata-v1m2-eclair-lin-grid-seed_1.py",
    (1, "dales"): "sonata-v1m2-dales-lin-grid-seed_1.py",
    (2, "h3d"): "litept-b-v1m0-h3d-lin-grid-seed_2.py",
    (2, "eclair"): "litept-b-v1m0-eclair-lin-grid-seed_2.py",
    (2, "dales"): "litept-b-v1m0-dales-lin-grid-seed_2.py",
    (3, "h3d"): "ptv3-v1m0-h3d-lin-grid-seed_3.py",
    (3, "eclair"): "ptv3-v1m0-eclair-lin-grid-seed_3.py",
    (3, "dales"): "ptv3-v1m0-dales-lin-grid-seed_3.py",
    (4, "h3d"): "kpconvx-v1m0-h3d-lin-grid-seed_4.py",
    (4, "eclair"): "kpconvx-v1m0-eclair-lin-grid-seed_4.py",
    (4, "dales"): "kpconvx-v1m0-dales-lin-grid-seed_4.py",
    (5, "h3d"): "spunet-v1m0-h3d-lin-grid-seed_5.py",
    (5, "eclair"): "spunet-v1m0-eclair-lin-grid-seed_5.py",
    (5, "dales"): "spunet-v1m0-dales-lin-grid-seed_5.py",
    (6, "h3d"): "litept-b-v1m0-h3d-lin-grid-seed-noGNL_6.py",
    (6, "eclair"): "litept-b-v1m0-eclair-lin-grid-seed-noGNL_6.py",
    (6, "dales"): "litept-b-v1m0-dales-lin-grid-seed-noGNL_6.py",
    (7, "h3d"): "litept-b-v1m0-h3d-lin-grid-seed-monoLC_7.py",
    (7, "eclair"): "litept-b-v1m0-eclair-lin-grid-seed-monoLC_7.py",
    (7, "dales"): "litept-b-v1m0-dales-lin-grid-seed-monoLC_7.py",
    (8, "h3d"): "litept-b-v1m0-h3d-lin-grid-seed-monoElev_8.py",
    (8, "eclair"): "litept-b-v1m0-eclair-lin-grid-seed-monoElev_8.py",
    (8, "dales"): "litept-b-v1m0-dales-lin-grid-seed-monoElev_8.py",
    (9, "h3d"): "litept-b-v1m0-h3d-lin-grid-seed-SS_9.py",
    (9, "eclair"): "litept-b-v1m0-eclair-lin-grid-seed-SS_9.py",
    (9, "dales"): "litept-b-v1m0-dales-lin-grid-seed-SS_9.py",
}


def main():
    for num_exp, slug, dataset, ref, lr in ROWS:
        text = read_ref(ref)
        out_text = transform(text, lr=lr, num_exp=num_exp)
        out_dir = REPO_ROOT / f"configs/experiment/w110/2/grid_seed_{dataset}"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / NAME_TEMPLATES[(num_exp, dataset)]
        out_path.write_text(out_text)
        print(f"wrote {out_path.relative_to(REPO_ROOT)}  (lr={lr}, ref={ref})")

    # Row 9 / ECLAIR: no existing SS reference config -- derive from the
    # ECLAIR "encoder" reference (dataset transforms/feat_scales/names) with
    # the SS backbone dict swapped in (same job 873542, dec_traceable=False
    # single-scale 72ch tap instead of the 1386ch encoder concat) — see
    # configs/h3d/litept-b-v1m0-h3d-lin_dec_ss.py /
    # configs/dales/litept-b-v1m0-dales-lin-grid-dec-ss.py for the pattern.
    # DERIVED, UNVERIFIED — double check before a JZ launch.
    eclair_enc_ref = REPO_ROOT / "configs/eclair/litept-b-v1m0-eclair-lin_enc.py"
    text = eclair_enc_ref.read_text()
    text = transform(text, lr=0.1, num_exp=9)

    old_backbone_out = (
        "# Encoder levels (enc_mode): 54+108+216+432+576 = 1386\n"
        "enc_channels = (54, 108, 216, 432, 576)\n"
        "backbone_out_channels = sum(enc_channels)"
    )
    new_backbone_out = (
        "# Final decoder stage only (dec_traceable=False): dec_channels[0]=72ch.\n"
        "# DERIVED/UNVERIFIED — no existing ECLAIR SS reference config; ported from\n"
        "# configs/h3d/litept-b-v1m0-h3d-lin_dec_ss.py & configs/dales/litept-b-v1m0-\n"
        "# dales-lin-grid-dec-ss.py (same job 873542 checkpoint). Double-check before launch.\n"
        "dec_channels = (72, 108, 216, 432)\n"
        "bottleneck_channels = 576\n"
        "backbone_out_channels = dec_channels[0]  # 72"
    )
    assert old_backbone_out in text, "ECLAIR encoder backbone_out_channels block shape changed"
    text = text.replace(old_backbone_out, new_backbone_out)

    old_backbone = """backbone=dict(
        type="LitePT-v1",
        in_channels=7,  # coord(3) + color(3) + strength(1)
        order=("z", "z-trans", "hilbert", "hilbert-trans"),
        stride=(3, 3, 3, 3),
        enc_depths=(3, 3, 3, 12, 3),
        enc_channels=enc_channels,
        enc_num_head=(3, 6, 12, 24, 32),
        enc_patch_size=(patch_size, patch_size, patch_size, patch_size, patch_size),
        enc_conv=(True, True, True, False, False),
        enc_attn=(False, False, False, True, True),
        enc_rope_freq=(100.0, 100.0, 100.0, 100.0, 100.0),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enc_mode=True,
    ),"""
    new_backbone = """backbone=dict(
        type="LitePT-v1",
        in_channels=7,  # coord(3) + color(3) + strength(1)
        order=("z", "z-trans", "hilbert", "hilbert-trans"),
        stride=(3, 3, 3, 3),
        enc_depths=(3, 3, 3, 12, 3),
        enc_channels=(54, 108, 216, 432, bottleneck_channels),
        enc_num_head=(3, 6, 12, 24, 32),
        enc_patch_size=(patch_size, patch_size, patch_size, patch_size, patch_size),
        enc_conv=(True, True, True, False, False),
        enc_attn=(False, False, False, True, True),
        enc_rope_freq=(100.0, 100.0, 100.0, 100.0, 100.0),
        dec_depths=(0, 0, 0, 0),
        dec_channels=dec_channels,
        dec_num_head=(4, 6, 12, 24),
        dec_patch_size=(patch_size, patch_size, patch_size, patch_size),
        dec_conv=(False, False, False, False),
        dec_attn=(False, False, False, False),
        dec_rope_freq=(100.0, 100.0, 100.0, 100.0),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enc_mode=False,
        dec_traceable=False,
    ),"""
    assert old_backbone in text, "ECLAIR encoder backbone dict shape changed"
    text = text.replace(old_backbone, new_backbone)

    out_dir = REPO_ROOT / "configs/experiment/w110/2/grid_seed_eclair"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / NAME_TEMPLATES[(9, "eclair")]
    out_path.write_text(text)
    print(f"wrote {out_path.relative_to(REPO_ROOT)}  (lr=0.1, DERIVED — no reference file)")


if __name__ == "__main__":
    main()
